### ISSUE TITLE
Install request: CPU & GPU version of Caffe

### ISSUE THREAD

**Issue by heatherkellyucl** [UCL-RITS/rcps-buildscripts#112]
IN:02540709

http://caffe.berkeleyvision.org/

The default instructions say they build both the CPU and non-cuDNN GPU version, so that should be fine. (We cannot install cuDNN centrally).

The GPU version may work with fewer CUDA threads on the older type V nodes (Compute Capability 2.0) but it is better suited to the type P.

**Comment by ikirker** [comment]
Hm, might be worth installing the [Intel branch](https://github.com/BVLC/caffe/tree/intel) separately.

**Comment by heatherkellyucl** [comment]
CuDNN can be installed centrally now, as an institution can be an NVIDIA registered developer.

**Comment by owainkenwayucl** [comment]
OK, having done Tensorflow etc. I guess I should do this.

**Comment by owainkenwayucl** [comment]
Instructions here: http://caffe.berkeleyvision.org/installation.html

**Comment by owainkenwayucl** [comment]
- [ ] - glog
- [ ] - gflags
- [ ] - lmdb

**Comment by owainkenwayucl** [comment]
OK, "glog" from that install page is here: https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/google-glog/glog-0.3.3.tar.gz

This is hosted on the Google code repository which appears to be archived here: https://code.google.com/archive/p/google-glog/

Version 0.3.3 is from 2013.

The archive page shows that it appears to now be on github here: https://github.com/google/glog

**Comment by owainkenwayucl** [comment]
OK, this is interesting.  The checksum for the v0.3.5 package given in arch aur doesn't match the file offered up by github, despite the entry in arch aur being allegedly newer.

**Comment by owainkenwayucl** [comment]
But the `md5sum` for the package in Ubuntu [artful|bionic] matches.

**Comment by owainkenwayucl** [comment]
OK, Glog installed.

**Comment by owainkenwayucl** [comment]
Gflags also has very confusing locations.

It looks like there are two repositories - the one suggested by the Caffe install and Arch AUR:

https://github.com/schuhschuh/gflags/

And the one suggested by Ubuntu, and by the Gflags website (http://gflags.github.io/gflags/):

https://github.com/gflags/gflags

The user schuhschuh appears to be legitmately the maintainer (as per the readme on the gflags repo) and his repo is a fork of the gflags repo but their copy has newer changes.

**Comment by owainkenwayucl** [comment]
Right.  Gflags is done.

**Comment by owainkenwayucl** [comment]
lmdb done.

**Comment by owainkenwayucl** [comment]
Right.

There are more dependencies:

- [ ] - protobuf
- [ ] - leveldb
- [ ] - snappy
- [ ] - opencv

**Comment by owainkenwayucl** [comment]
I wonder what the most sensible way to install Google protobuf is...

**Comment by owainkenwayucl** [comment]
OK, it looks like we have modules for protobuf and opencv already.

So it's just "leveldb" and "snappy".

**Comment by owainkenwayucl** [comment]
So.

LevelDB appears to be:

https://github.com/google/leveldb

Snappy appears to be: 

https://github.com/google/snappy/

**Comment by owainkenwayucl** [comment]
Right, LevelDB and Snappy are installed on Legion/Grace.  Thomas is down for maintenence.

**Comment by owainkenwayucl** [comment]
Right - it looks like our protocol buffer install is very specific to the R installation.

**Comment by owainkenwayucl** [comment]
Current problem is that our build of OpenCV is wrapped around Python 2.

**Comment by owainkenwayucl** [comment]
Caffe builds, if you fiddle the directories that leveldb adds to remove the static libraries (don't ask) but the tests don't.

**Comment by owainkenwayucl** [comment]
Module list:

```
rcps-core/1.0.0
compilers/gnu/4.9.2
python/3.6.3
openblas/0.2.14/gnu-4.9.2
python3/3.6
python3/recommended
opencv/3.4.1/gnu-4.9.2
protobuf/3.5.1/gnu-4.9.2
snappy/1.1.7
gflags/2.2.1
leveldb/1.20
glog/0.3.5
lmdb/0.9.22
boost/1_63_0/gnu-4.9.2
hdf/5-1.8.15/gnu-4.9.2
```

**Comment by owainkenwayucl** [comment]
So let's assume that's the CPU version built.

Now I need to do two GPU versions on Legion because Caffe has two alternate GPU implementations, one using CudaNN and one not, which are optimal on different types of problem.

**Comment by owainkenwayucl** [comment]
I guess I should try and get the tests to build.

**Comment by owainkenwayucl** [comment]
Hmm.  The way they are failing now is... different.

**Comment by owainkenwayucl** [comment]
The opencv module is lacking `lib64` where its libraries actually are.

**Comment by owainkenwayucl** [comment]
And that seems to have fixed the other problem.  Tests are now running.

**Comment by owainkenwayucl** [comment]
Now I need to do the GPU version.

**Comment by owainkenwayucl** [comment]
Well that's not cool:

```
/shared/ucl/apps/cuda/8.0.61/gnu-4.9.2/include/cuda_fp16.h(2903): error: calling a __device__ function("__fmaf_rn") from a __host__ function("hdiv") is not allowed

/shared/ucl/apps/cuda/8.0.61/gnu-4.9.2/include/cuda_fp16.h(2904): error: calling a __device__ function("__fmaf_rn") from a __host__ function("hdiv") is not allowed

/shared/ucl/apps/cuda/8.0.61/gnu-4.9.2/include/cuda_fp16.h(2958): error: calling a __device__ function("__float2half_rn") from a __host__ function("__hsin_internal") is not allowed

/shared/ucl/apps/cuda/8.0.61/gnu-4.9.2/include/cuda_fp16.h(3000): error: calling a __device__ function("__float2half_rn") from a __host__ function("__hcos_internal") is not allowed

/shared/ucl/apps/cuda/8.0.61/gnu-4.9.2/include/cuda_fp16.h(3033): error: calling a __device__ function("__float2int_rn") from a __host__ function("__internal_trig_reduction_kernel") is not allowed

/shared/ucl/apps/cuda/8.0.61/gnu-4.9.2/include/cuda_fp16.h(3035): error: calling a __device__ function("__fmaf_rn") from a __host__ function("__internal_trig_reduction_kernel") is not allowed

/shared/ucl/apps/cuda/8.0.61/gnu-4.9.2/include/cuda_fp16.h(3036): error: calling a __device__ function("__fmaf_rn") from a __host__ function("__internal_trig_reduction_kernel") is not allowed

/shared/ucl/apps/cuda/8.0.61/gnu-4.9.2/include/cuda_fp16.h(3047): error: calling a __device__ function("__fmaf_rn") from a __host__ function("__internal_sin_cos_kernel") is not allowed

/shared/ucl/apps/cuda/8.0.61/gnu-4.9.2/include/cuda_fp16.h(3050): error: calling a __device__ function("__fmaf_rn") from a __host__ function("__internal_sin_cos_kernel") is not allowed

/shared/ucl/apps/cuda/8.0.61/gnu-4.9.2/include/cuda_fp16.h(3053): error: calling a __device__ function("__fmaf_rn") from a __host__ function("__internal_sin_cos_kernel") is not allowed

/shared/ucl/apps/cuda/8.0.61/gnu-4.9.2/include/cuda_fp16.h(3054): error: calling a __device__ function("__fmaf_rn") from a __host__ function("__internal_sin_cos_kernel") is not allowed

/shared/ucl/apps/cuda/8.0.61/gnu-4.9.2/include/cuda_fp16.h(3056): error: calling a __device__ function("__fmaf_rn") from a __host__ function("__internal_sin_cos_kernel") is not allowed

/shared/ucl/apps/cuda/8.0.61/gnu-4.9.2/include/cuda_fp16.h(3057): error: calling a __device__ function("__fmaf_rn") from a __host__ function("__internal_sin_cos_kernel") is not allowed

/shared/ucl/apps/cuda/8.0.61/gnu-4.9.2/include/cuda_fp16.h(3059): error: calling a __device__ function("__fmaf_rn") from a __host__ function("__internal_sin_cos_kernel") is not allowed

/shared/ucl/apps/cuda/8.0.61/gnu-4.9.2/include/cuda_fp16.h(3060): error: calling a __device__ function("__fmaf_rn") from a __host__ function("__internal_sin_cos_kernel") is not allowed

/shared/ucl/apps/cuda/8.0.61/gnu-4.9.2/include/cuda_fp16.h(3061): error: calling a __device__ function("__fmaf_rn") from a __host__ function("__internal_sin_cos_kernel") is not allowed

/shared/ucl/apps/protobuf/3.5.1/gnu-4.9.2/include/google/protobuf/arena_impl.h(54): warning: integer conversion resulted in a change of sign

/shared/ucl/apps/protobuf/3.5.1/gnu-4.9.2/include/google/protobuf/arena_impl.h(232): warning: integer conversion resulted in a change of sign

16 errors detected in the compilation of "/tmp/tmpxft_00001cec_00000000-5_hdf5_data_layer.cpp4.ii".
make: *** [.build_release/cuda/src/caffe/layers/hdf5_data_layer.o] Error 1
```

**Comment by owainkenwayucl** [comment]
This also happens with the cudnn build.  I guess this means I need to rebuild one of dependencies with Cuda support...

**Comment by owainkenwayucl** [comment]
Right, for anyone who finds this, the problem was Cuda 8.

I've just done a build with Cuda 7.5.18 and:

```
[----------] Global test environment tear-down
[==========] 1106 tests from 150 test cases ran. (69471 ms total)
[  PASSED  ] 1106 tests.
```

**Comment by owainkenwayucl** [comment]
Right.  I switched fro Cuda 8.x to Cuda 7.5.18 and it looks like it built overnight, unfortunately the tests failed because of a problem on the node so I'm waiting for that to be resolved before I go forward.

**Comment by owainkenwayucl** [comment]
CUDA build:

```
[----------] Global test environment tear-down
[==========] 2041 tests from 267 test cases ran. (594528 ms total)
[  PASSED  ] 2041 tests.
```

Now to do CudNN.

**Comment by owainkenwayucl** [comment]
```
[----------] Global test environment tear-down
[==========] 2101 tests from 277 test cases ran. (647339 ms total)
[  PASSED  ] 2101 tests.
```

CudNN build done.

Caffe is completed.
