### ISSUE TITLE
Install Quantum Espresso 6.3 with d3q add-in

### ISSUE THREAD

**Issue by heatherkellyucl** [UCL-RITS/rcps-buildscripts#111]
IN:02501340
(Request originally to add d3q to existing Quantum Espresso 6.1 install).

https://sourceforge.net/projects/d3q/

Licenses: CeCILL Free Software license V2.1, GPL

This looks fine - it adds a d3q.x

**Comment by heatherkellyucl** [comment]
This does need to be built at the same time as Quantum Espresso though - you put it inside the QE top level directory and build it there as it looks for the rest of the source code.

There's a QE 6.2 out so I guess I could build it and the version of d3q that goes with that.

**Comment by heatherkellyucl** [comment]
We were including West in our Quantum Espresso builds - this is pulled in from another repository and does not appear to be working with QE 6.2 at present.

Error during build. Configure and make lines were:
```
./configure --prefix=/dev/shm/qe-install FFLAGS="-fp-model strict" --enable-parallel --with-scalapack=intel FFT_LIBS=-lfftw3xf_intel
make all w90 want west couple gui 2>&1 | tee make.log
```

```
mpif90 -fp-model strict -nomodule -fpp -D__DFTI -D__MPI -D__SCALAPACK   -I../../iotk/src -I../../Modules -I.
./../LAXlib -I../../FFTXlib -I../../PW/src -I../Modules -I. -c exx_go.f90
exx_go.f90(21): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [PARALLEL_IN
CLUDE]
  USE fft_base,               ONLY : dfftp,dffts
------^
...
/tmp/ifortXYcKXe.i90(74): catastrophic error: Too many errors, exiting
compilation aborted for exx_go.f90 (code 1)
make[3]: Leaving directory `/dev/shm/qe-6.2.1/West/Tools
```
From https://www.mail-archive.com/pw_forum@pwscf.org/msg33268.html
2 Jan 2018
>The advise from Marco Govoni is to use QE version 6.1. I was able to compile WEST within QE 6.1.

So I won't make WEST at present.

**Comment by heatherkellyucl** [comment]
d3q is listed in the third party packages choices in the Makefile, so we can include `make d3q` in the list.

**Comment by heatherkellyucl** [comment]
```
mpif90 -fp-model strict -nomodule -fpp -D__DFTI -D__MPI -D__SCALAPACK   -I../../iotk/src -I../../Modules -I../../FFTXlib -I../../UtilXlib -I../../CPV/src -c libpwscf.f90
libpwscf.f90(51): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [MP_DIAG]
  USE mp_global,         ONLY : mp_startup
------^

...

compilation aborted for libpwscf.f90 (code 1)
make[2]: *** [libpwscf.o] Error 1
make[2]: Leaving directory `/dev/shm/qe-6.2.1/COUPLE/src'
```

**Comment by heatherkellyucl** [comment]
```
Known problems in 6.2.1 version:

  * pw2bgw.x not working

  * QM-MM not yet working; COUPLE interface not aligned with new parallelism

  * New format for charge density no longer allows to perform a non-scf
    calculation with k-points starting from a scf calculation at Gamma

  * NEB with one k-point per pool requires "wf_collect=.false.", because
    update_neb is not updated for the new format
```
So `couple` also needs to be left out.

**Comment by heatherkellyucl** [comment]
Maybe this should be waiting until 6.2.2 for a central install.

**Comment by ikirker** [comment]
6.3 released, build with d3q if compatible.
