### ISSUE TITLE
Install Request: Quantum Espresso 6.4 [IN04015177]

### ISSUE THREAD

**Issue by hillary-b** [UCL-RITS/rcps-buildscripts#318]

**Comment by owainkenwayucl** [comment]
Doing test builds for this for other reasons so taking this on.

**Comment by owainkenwayucl** [comment]
The nice thing is, with Intel 2018 QE 6.4.1 passes all its tests.

**Comment by owainkenwayucl** [comment]
As does 6.5 so I'll do that as well.

**Comment by owainkenwayucl** [comment]
6.4.1 deployed.

**Comment by owainkenwayucl** [comment]
6.5 also deployed.

Myriad needs the modules installed when it gets over its DNS woes.

**Comment by owainkenwayucl** [comment]
Myriad modules installed too.

**Comment by hillary-b** [comment]
User has been informed

**Comment by heatherkellyucl** [comment]
Bug in QE linking is affecting all our 6.x installs:

dos.x, bands.x and wannier90.x are all incorrectly linked to the versions inside WANT instead of the normal versions.

https://lists.quantum-espresso.org/pipermail/developers/2014-September/000752.html
https://lists.quantum-espresso.org/pipermail/developers/2014-September/000753.html

**Comment by heatherkellyucl** [comment]
I think we need to check if `make all w90 want west couple gui epw d3q` is still necessary rather than `make all`.

**Comment by heatherkellyucl** [comment]
The workaround for name conflicts with WANT is in https://github.com/QEF/q-e/blob/qe-6.0.0/Makefile so I think the problem is with our make command - maybe the order?

**Comment by heatherkellyucl** [comment]
'make all' is the same as `make pwall cp ld1 upf tddfpt`
and `make pwall` is `make pw ph pp pwcond neb` so yes, those other things do need to be included separately.

**Comment by heatherkellyucl** [comment]
The workaround exists in `make links` which we are **not** doing.

**Comment by heatherkellyucl** [comment]
The main confusion is that `make install` doesn't carry out `make links` first, really.

**Comment by heatherkellyucl** [comment]
Nope, `make install` isn't compatible with `make links` first and still results in this:
```
‘PP/src/dos.x’ -> ‘/home/cceahke/qe-install/bin/dos.x’
‘PP/src/bands.x’ -> ‘/home/cceahke/qe-install/bin/bands.x’
...
‘want/src/wannier/dos.x’ -> ‘/home/cceahke/qe-install/bin/dos.x’
‘want/src/wannier/cmplx_bands.x’ -> ‘/home/cceahke/qe-install/bin/cmplx_bands.x’
‘want/src/wannier/bands.x’ -> ‘/home/cceahke/qe-install/bin/bands.x’
```

**Comment by heatherkellyucl** [comment]
`make install` considered harmful; building in place.

**Comment by heatherkellyucl** [comment]
Argh, the West source code has moved (this is for a 6.4.1 install attempt).
```
gzip: ../archive/West-2.0.1.tar.gz: not in gzip format
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
*** Unable to download http://www.west-code.org/downloads/West-2.0.1.tar.gz.
*** Verify that the url is correct.
make[1]: *** [uncompress-west] Error 1
make[1]: Leaving directory `/lustre/home/cceahke/qe-install/q-e/install'
make: *** [west] Error 1
```
It is now in `http://west-code.org/download/West/v2.0.1/West-2.0.1.tar.gz` instead.

**Comment by heatherkellyucl** [comment]
```
if test ! -e ../West; then (gzip -dc ../archive/`echo "http://www.west-code.org/downloads/West-2.0.1.tar.gz" | sed 's/.*\///;s/.*=//'` | (cd ../ ; tar -xvf - ) ) ; if test "`echo $?`" -ne "0" ; then echo "*** Unable to download http://www.west-code.org/downloads/West-2.0.1.tar.gz." ; echo "*** Verify that the url is correct." ; exit 1 ; else (cd ../ ; ln -s West-2.0.1 West) ; fi ; fi
```
We can make West exist in the right place ourselves, I guess.

**Comment by heatherkellyucl** [comment]
Currently checking that my fixed build of 6.4.1 works.

**Comment by heatherkellyucl** [comment]
Failure during building West's tools:
```
mpif90 -fp-model precise -nomodule -fpp -D__DFTI -D__MPI -D__SCALAPACK    -I../../iotk/src -I../../Modules -
I../../LAXlib -I../../FFTXlib -I../../PW/src -I../Modules -I. -c exx_go.f90
exx_go.f90(21): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [PARALLEL_IN
CLUDE]
  USE fft_base,               ONLY : dfftp,dffts
------^
exx_go.f90(41): error #6404: This name does not have a type, and must have an explicit type.   [EXXDIV_TREAT
MENT]
     exxdiv_treatment='gb'
-----^
exx_go.f90(43): error #6404: This name does not have a type, and must have an explicit type.   [ERFC_SCRLEN]
     erfc_scrlen = get_screening_parameter()

...

exx_go.f90(21): error #6580: Name in only-list does not exist or is not accessible.   [DFFTP]
  USE fft_base,               ONLY : dfftp,dffts
-------------------------------------^
exx_go.f90(21): error #6580: Name in only-list does not exist or is not accessible.   [DFFTS]
  USE fft_base,               ONLY : dfftp,dffts
-------------------------------------------^
exx_go.f90(22): error #6580: Name in only-list does not exist or is not accessible.   [X_GAMMA_EXTRAPOLATION]
  USE exx,                    ONLY : x_gamma_extrapolation,exxdiv_treatment,exx_grid_init,exx_div_check,exx_divergence,&
-------------------------------------^

...

/tmp/ifortZHc4Y2.i90(74): catastrophic error: Too many errors, exiting
compilation aborted for exx_go.f90 (code 1)
make[3]: *** [exx_go.o] Error 1
make[3]: Leaving directory `/lustre/home/cceahke/qe-install-2/q-e/West/Tools'
make[2]: *** [tools_do] Error 2
make[2]: Leaving directory `/lustre/home/cceahke/qe-install-2/q-e/West'
make[1]: *** [west] Error 1
make[1]: Leaving directory `/lustre/home/cceahke/qe-install-2/q-e/install'
make: *** [west] Error 1
```
Maybe should leave out West, since we haven't had a working install of it and no one is using it just now. `bands.x` is now the correct binary.

**Comment by heatherkellyucl** [comment]
In this thread from 2018, WEST works with QE 6.1 but not 6.2.1

https://lists.quantum-espresso.org/pipermail/users/2018-January/040042.html
https://lists.quantum-espresso.org/pipermail/users/2018-January/040046.html

> The advise from Marco Govoni is to use QE version 6.1. I was able to compile WEST within QE 6.1.

Going to remove it from the later builds.

**Comment by heatherkellyucl** [comment]
The 6.4.1. build appears to all be fine now. (Building takes so long!)

Install fixed 6.4.1 version centrally on 
- [ ] Kathleen
- [ ] Grace
- [ ] Thomas
- [ ] Myriad
- [ ] Legion (since it is already there)
- [ ] update modulefile to point at fixed one

Then I need to look at the 6.1 and 6.5 installs. The separate thermo-pw installs are fine (or at least don't have the bands.x conflict) because they don't include WANT.

**Comment by heatherkellyucl** [comment]
No, the thermo-pw ones do need fixing, but for the opposite reason it appears. They have the correct bands.x so won't have the WANT versions.

**Comment by heatherkellyucl** [comment]
6.4.1 building everywhere.

**Comment by heatherkellyucl** [comment]
Install fixed 6.5 version centrally on 
- [ ] Kathleen
- [ ] Grace
- [ ] Thomas
- [ ] Myriad
- [ ] Legion (since it is already there)
- [ ] update modulefile to point at fixed one

Install fixed 6.1 version centrally on 
- [ ] Kathleen
- [ ] Grace
- [ ] Thomas
- [ ] Myriad
- [ ] Legion (since it is already there)
- [ ] update modulefile to point at fixed one

Install fixed 6.3-thermo version centrally on 
- [ ] Kathleen
- [ ] Grace
- [ ] Thomas
- [ ] Myriad
- [ ] update modulefile to point at fixed one

Install fixed 6.5-thermo version centrally on 
- [ ] Kathleen
- [ ] Grace
- [ ] Thomas
- [ ] Myriad
- [ ] update modulefile to point at fixed one

**Comment by heatherkellyucl** [comment]
Test building the 6.3-thermo_pw version.
