### ISSUE TITLE
Install Request: up to date version of Rust compiler

### ISSUE THREAD

**Issue by heatherkellyucl** [UCL-RITS/rcps-buildscripts#350]
IN: 04252460

User wanted to install https://github.com/10XGenomics/scHLAcount#using-schlacount, but the binary needs a newer GLIBC and compiling with `compilers/rust/1.18.0` gives errors:

```
error: unexpected token: `=`
    --> /home/regmgbe/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-syntax-0.6.11/src/ast/parse.rs:1440:16
     |
1440 |             '0'..='7' => {
     |                ^^

   Compiling arrayvec v0.4.11
error[E0432]: unresolved import `core::sync::atomic::spin_loop_hint`
 --> /home/regmgbe/.cargo/registry/src/github.com-1ecc6299db9ec823/spin-0.4.10/src/mutex.rs:1:66
  |
1 | use core::sync::atomic::{AtomicBool, Ordering, ATOMIC_BOOL_INIT, spin_loop_hint as cpu_relax};
  |                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `spin_loop_hint` in `sync::atomic`

```

Needs newer Rust.

**Comment by heatherkellyucl** [comment]
Their documentation may be out of date:

> scHLAcount is a standard Rust executable project, that works with stable Rust >=1.13.

**Comment by heatherkellyucl** [comment]
`core::sync::atomic::spin_loop_hint` was stable since Rust 1.24.0

**Comment by ikirker** [comment]
1.46.0 installed everywhere but Grace and Legion (they're still down).

**Comment by heatherkellyucl** [comment]
Done in Sept and Grace is retired so doesn't need installing there.
