### ISSUE TITLE
Install Request: EnergyPlus (IN:03763195)

### ISSUE THREAD

**Issue by ikirker** [UCL-RITS/rcps-buildscripts#294]
Application: EnergyPlus

Link: <https://energyplus.net/>
But also: <https://github.com/NREL/EnergyPlus/releases>

Description: EnergyPlus™ is a whole building energy simulation program that engineers, architects, and researchers use to model both energy consumption—for heating, cooling, ventilation, lighting and plug and process loads—and water use in buildings.

License: open source, [permissive BSD-style](https://energyplus.net/licensing).

Ticket number: IN:03763195

**Comment by ikirker** [comment]
Currently I'm seeing an error during the compilation:
```
In file included from /home/uccaiki/Downloads/e/EnergyPlus-9.1.0/third_party/eigen/Eigen/SparseCore:40:0,
                 from /home/uccaiki/Downloads/e/EnergyPlus-9.1.0/third_party/kiva-ep/src/libkiva/Cell.hpp:18,
                 from /home/uccaiki/Downloads/e/EnergyPlus-9.1.0/third_party/kiva-ep/src/libkiva/Domain.hpp:7,
                 from /home/uccaiki/Downloads/e/EnergyPlus-9.1.0/third_party/kiva-ep/src/libkiva/Ground.hpp:9,
                 from /home/uccaiki/Downloads/e/EnergyPlus-9.1.0/third_party/kiva-ep/src/libkiva/Aggregator.hpp:7,
                 from /home/uccaiki/Downloads/e/EnergyPlus-9.1.0/src/EnergyPlus/HeatBalanceKivaManager.hh:52,
                 from /home/uccaiki/Downloads/e/EnergyPlus-9.1.0/src/EnergyPlus/SurfaceGeometry.hh:59,
                 from /home/uccaiki/Downloads/e/EnergyPlus-9.1.0/src/EnergyPlus/ConvectionCoefficients.cc:79:
/home/uccaiki/Downloads/e/EnergyPlus-9.1.0/third_party/eigen/Eigen/src/SparseCore/AmbiVector.h: In member function ‘_Scalar& Eigen::internal::AmbiVector<_Scalar, _StorageIndex>::coeff(Eigen::Index)’:
/home/uccaiki/Downloads/e/EnergyPlus-9.1.0/third_party/eigen/Eigen/src/SparseCore/AmbiVector.h:270:44: error: parse error in template argument list
       while (elid >= 0 && llElements[elid].index<i)
                                            ^
make[2]: *** [src/EnergyPlus/CMakeFiles/energypluslib.dir/ConvectionCoefficients.cc.o] Error 1
make[1]: *** [src/EnergyPlus/CMakeFiles/energypluslib.dir/all] Error 2
```

My C++ isn't so great, but I'm going to check whether this is caused by Eigen using a new C++ feature that our old version of GCC (4.9.2) doesn't support, by trying again with GCC 8.3.0.

**Comment by ikirker** [comment]
Yeah, the same cmake settings that work with 8.3.0 fail with 4.9.2. And if you use the binary distribution, it complains with 4.9.2 that a sufficiently high version of the CXXLIB symbols isn't available.

It might be better to use the binary distribution in any case: there are some dataset files in there that the from-source build doesn't install and that I'm not sure where to take from.

**Comment by ikirker** [comment]
Installed binary distribution everywhere.
