### ISSUE TITLE
Install request: Boost 1.6x

### ISSUE THREAD

**Issue by heatherkellyucl** [UCL-RITS/rcps-buildscripts#89]
IN:02351520
Require 1.58 or later and would like a recent version such as 1.63. (1.64 came out yesterday, so we could do that).

http://www.boost.org/users/history/version_1_63_0.html

**Comment by heatherkellyucl** [comment]
Going with 1.64.

**Comment by heatherkellyucl** [comment]
It looks like there are a couple of minor changes in build options - if using mpi you modify the main project-config.jam now instead of user-config.jam, and the intel toolset name has changed from intel-linux to intel.

Doing a test build with gcc and openmpi 1.10 now.

**Comment by heatherkellyucl** [comment]
It also appears that they've broken the mpi builds in the current release...

```
./boost/mpi/detail/mpi_datatype_primitive.hpp:28:51: fatal error: boost/serialization/detail/get_data.hpp: N
o such file or directory
 #include <boost/serialization/detail/get_data.hpp>
                                                   ^
compilation terminated.
```
https://svn.boost.org/trac/boost/ticket/12723

So I'll go back to 1.63.

**Comment by heatherkellyucl** [comment]
That built fine for 1.63, so I can set the proper installs going.

**Comment by heatherkellyucl** [comment]
- [ ] gnu nompi
- [ ] gnu mpi
- [ ] intel mpi

on Grace and Legion.

**Comment by heatherkellyucl** [comment]
Requestor was informed, no reports of it being broken, closing.
