### ISSUE TITLE
Install Request: Update JAGS to > 4.3.0 [IN04603501]

### ISSUE THREAD

**Issue by balston** [UCL-RITS/rcps-buildscripts#428]
Current versions on Myriad do not support what user needs.

https://sourceforge.net/projects/mcmc-jags/files/JAGS/

**Comment by balston** [comment]
Updating the build script _jags-4.2.0_install_ to build the latest 4.3.0 version.

**Comment by balston** [comment]
Build script updated and uploaded to Myriad. Running:
```
cd /shared/ucl/apps/build_scripts
./jags-4.3.0_install 2>&1 | tee ~/Software/jags-4.3.0_install.log-04052021
```

**Comment by balston** [comment]
Build finished without errors but the tests were not run so need to update the build script and re-run.

**Comment by balston** [comment]
Its now reaching the tests direfctory but I'm getting the following error:
```
make  check-TESTS
make[2]: Entering directory `/dev/shm/tmp.wL5qVu0o40/JAGS-4.3.0/test'
make[3]: Entering directory `/dev/shm/tmp.wL5qVu0o40/JAGS-4.3.0/test'
/bin/sh ../libtool  --tag=CXX   --mode=link g++  -g -O2   -o base
libtool: link: g++ -g -O2 -o base
g++: fatal error: no input files
compilation terminated.
make[3]: *** [base] Error 1
make[3]: Leaving directory `/dev/shm/tmp.wL5qVu0o40/JAGS-4.3.0/test'
make[2]: *** [check-TESTS] Error 2
make[2]: Leaving directory `/dev/shm/tmp.wL5qVu0o40/JAGS-4.3.0/test'
make[1]: *** [check-am] Error 2
make[1]: Leaving directory `/dev/shm/tmp.wL5qVu0o40/JAGS-4.3.0/test'
make: *** [check-recursive] Error 1
```
and the build script aborts. Investigating ...

**Comment by balston** [comment]
I made a slight error so now I get:
```
============================================================================
Testsuite summary for JAGS 4.3.0
============================================================================
# TOTAL: 0
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
```
So not running any tests but not aborting either.

Looks like something in the configure step is disabling checking. Having as look to see if there is an option to switch it on.

**Comment by balston** [comment]
I think I've discovered the problem. In the output from running configure there is:
```
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for CPPUNIT... no
```

**Comment by balston** [comment]
I couldn't find CppUnit on the Cluster. We only have CUnit as far as could see. I will  try and build CppUnit.

**Comment by balston** [comment]
Produced build script for CppUnit 1.15.1 the latest released version. Building:
```
./cppunit-1.15.1_install 2>&1 | tee ~/Software/cppunit-1.15.1_install.log-05052021-1
```

**Comment by balston** [comment]
Appears to have built OK and passed the make check step. Now doing a module file.

**Comment by balston** [comment]
Added loading module:
```
require cppunit/1.15.1/gnu-4.9.2
```
to _jags-4.3.0_install_ build script. Rerunning build script.

**Comment by balston** [comment]
Didn't work. I'm getting these errors from make check now:
```
make[4]: Entering directory `/dev/shm/tmp.x57IGEpA5K/JAGS-4.3.0/src/lib/function'
/bin/sh ../../../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I../../..  -I../../../src/include  -I/shared/ucl/apps/CppUnit/1.15.1/include   -g -O2 -MT libfuntest_la-testfun.lo -MD -MP -MF .deps/libfuntest_la-testfun.Tpo -c -o libfuntest_la-testfun.lo `test -f 'testfun.cc' || echo './'`testfun.cc
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I../../.. -I../../../src/include -I/shared/ucl/apps/CppUnit/1.15.1/include -g -O2 -MT libfuntest_la-testfun.lo -MD -MP -MF .deps/libfuntest_la-testfun.Tpo -c testfun.cc  -fPIC -DPIC -o .libs/libfuntest_la-testfun.o
In file included from /lustre/shared/ucl/apps/gcc/4.9.2/include/c++/4.9.2/type_traits:35:0,
                 from /shared/ucl/apps/CppUnit/1.15.1/include/cppunit/tools/StringHelper.h:7,
                 from /shared/ucl/apps/CppUnit/1.15.1/include/cppunit/TestAssert.h:8,
                 from /shared/ucl/apps/CppUnit/1.15.1/include/cppunit/TestCase.h:6,
                 from /shared/ucl/apps/CppUnit/1.15.1/include/cppunit/TestCaller.h:5,
                 from /shared/ucl/apps/CppUnit/1.15.1/include/cppunit/extensions/HelperMacros.h:9,
                 from testfun.cc:5:
/lustre/shared/ucl/apps/gcc/4.9.2/include/c++/4.9.2/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
```
I'm next going to try building with GNU 10.2.0.

**Comment by balston** [comment]
Will need to build CppUnit with GNU 10.2.0 first.

**Comment by balston** [comment]
CppUnit built with GNU 10.2.0 done. Module file:
```
module load cppunit/1.15.1/gnu-10.2.0
```

**Comment by balston** [comment]
I've done a test build of JAGS in my HOME with GNU 10.2.0 and the above CppUnit and it builds and passes the test suite:
```
make[3]: Entering directory `/lustre/scratch/scratch/ccaabaa/Software/JAGS/build/JAGS-4.3.0/test'
PASS: base
PASS: bugs
PASS: mix
PASS: glm
============================================================================
Testsuite summary for JAGS 4.3.0
============================================================================
# TOTAL: 4
# PASS:  4
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
```
I'm now going to update the build script and do the /shared/ucl/apps build with GNU 10.2.0.

**Comment by balston** [comment]
I've just noticed the title has the minor version numbers the wrong way round! Corrected.

**Comment by balston** [comment]
Now re-running build script with:
```
module -f unload compilers mpi gcc-libs
module load beta-modules
./jags-4.3.0_install 2>&1 | tee ~/Software/jags-4.3.0_install.log-06052021
```

**Comment by balston** [comment]
Builds and runs the tests without errors at last! Now to produce a module file for this version.

**Comment by balston** [comment]
Module file uploaded to Myriad. Will need to use these module commands:
```
module -f unload compilers mpi gcc-libs
module load gcc-libs/10.2.0
module load openblas/0.3.13-native-threads/gnu-10.2.0
module load jags/4.3.0/gnu-10.2.0-openblas
```

**Comment by balston** [comment]
Done on Myriad and user informed.

Now install everywhere:
- [ ] Aristole/RStudio;
- [ ] Kathleen;
- [ ] Michael;
- [ ] Myriad;
- [ ] Thomas;
- [ ] Young,

**Comment by balston** [comment]
So I think the following needs to be done on each cluster:
```
cd /shared/ucl/apps/build_scripts
git pull
module -f unload compilers mpi gcc-libs
./cppunit-1.15.1-gnu1020_install 2>&1 | tee ~/Software/cppunit-1.15.1-gnu1020_install.log
../update_modules
./jags-4.3.0_install 2>&1 | tee ~/Software/jags-4.3.0_install.log
../update_modules
```
I think.

**Comment by balston** [comment]
Just need to wait for the others to sync. Michael should happen by tomorrow and Aristole/RStudio will need to be requested next week.
